// Generated by https://quicktype.io

export interface HeroInterface {
  _id?: string;
  superhero: string;
  publisher: string;
  alterEgo: string;
  firstAppearance: string;
  characters: string;
  photo?: string;
  // __v:             number;
}
